(function (win, ysp) {
  ysp.runtime.Model.extendLoadingModel({
    getData_control0_hCU0e9: function (elem) {
      if (!elem) {
        return false;
      }var data = [];var elem = $(elem) && $(elem).find('table');var trs = $(elem).find('tr');var obj = {};obj.value = $(trs) && $(trs).eq(2).find('input').eq(0).val();data.push(obj);var obj = {};obj.value = $(trs) && $(trs).eq(3).find('input').eq(0).val();data.push(obj);var obj = {};obj.value = $(trs) && $(trs).eq(0).find('font').eq(0).text();data.push(obj);return data;
    },
    doAction_uiControl0_UK1PTt: function (data, elem) {
      if (data.eventType == 'nameValue') {
        var data = data.dataCustom;var elem = $(elem) && $(elem).find('table');$(elem).find('tr').eq(2).find('input').eq(0).val(data);
      } else if (data.eventType == 'password') {
        var data = data.dataCustom;var elem = $(elem) && $(elem).find('table');$(elem).find('tr').eq(3).find('input').eq(0).val(data);
      } else if (data.eventType == 'button') {
        var elem = $(elem) && $(elem).find('table');$(elem).find('tr').eq(5).find('input').eq(0).click(); //计时器处理:如果用户名或者密码输入错误，组件模板不会随pc同步需要重新点击一次
        var times = setTimeout(function () {
          $(elem).find('tr').eq(5).find('input').eq(0).click();
        }, 1000);
      }
    },
    getTemplate_uiControl0_UK1PTt: function () {
      var selfTemplate = "\nmodule.exports = React.createClass({\n  nameValue:function(e){\n    var handler=this.props.customHandler;\n    if(handler){\n      handler({\n        eventType:'nameValue',\n        data:e.target.value\n      })\n    }\n  }, \n  password:function(e){\n    var handler=this.props.customHandler;\n    if(handler){\n      handler({\n        eventType:'password',\n        data:e.target.value\n      })\n    }\n  },\n  button:function(e){\n    var handler =this.props.customHandler;\n    if(handler){\n      handler({\n        eventType:'button',\n        data:''\n      })\n    }\n  },\n  render: function() {\n    var data =this.props.customData;\n    var _this = this;\n    if(data&&data[0]&&data[1]){\n     return (\n      <div className='d_denglu'>\n        <div className='d_denglu2'>\n          <div className='logo'></div>\n          <div>\u90AE\u4EF6\u7CFB\u7EDF</div>\n          <div className='userPassword'>\n            <span className='user'></span>\n            <AInput value={data[0].value} onChange={_this.nameValue} type='text'/>\n          </div>\n          <div className='userPassword'>\n            <span className='password'></span>\n            <AInput value={data[1].value} onChange={_this.password} type='password'/>\n          </div>\n          <div className='login_alert'>{data[2].value}</div>\n          <div className='denglu' onClick={_this.button}>\u767B\u5F55</div>\n        </div>\n      </div>\n    )\n    }else {\n      return <div></div>\n    }\n\n  }\n});\n";
      return "'use strict';\n\nmodule.exports = React.createClass({\n  displayName: 'exports',\n\n  nameValue: function nameValue(e) {\n    var handler = this.props.customHandler;\n    if (handler) {\n      handler({\n        eventType: 'nameValue',\n        data: e.target.value\n      });\n    }\n  },\n  password: function password(e) {\n    var handler = this.props.customHandler;\n    if (handler) {\n      handler({\n        eventType: 'password',\n        data: e.target.value\n      });\n    }\n  },\n  button: function button(e) {\n    var handler = this.props.customHandler;\n    if (handler) {\n      handler({\n        eventType: 'button',\n        data: ''\n      });\n    }\n  },\n  render: function render() {\n    var data = this.props.customData;\n    var _this = this;\n    if (data && data[0] && data[1]) {\n      return React.createElement(\n        'div',\n        { className: 'd_denglu' },\n        React.createElement(\n          'div',\n          { className: 'd_denglu2' },\n          React.createElement('div', { className: 'logo' }),\n          React.createElement(\n            'div',\n            null,\n            '\\u90AE\\u4EF6\\u7CFB\\u7EDF'\n          ),\n          React.createElement(\n            'div',\n            { className: 'userPassword' },\n            React.createElement('span', { className: 'user' }),\n            React.createElement(AInput, { value: data[0].value, onChange: _this.nameValue, type: 'text' })\n          ),\n          React.createElement(\n            'div',\n            { className: 'userPassword' },\n            React.createElement('span', { className: 'password' }),\n            React.createElement(AInput, { value: data[1].value, onChange: _this.password, type: 'password' })\n          ),\n          React.createElement(\n            'div',\n            { className: 'login_alert' },\n            data[2].value\n          ),\n          React.createElement(\n            'div',\n            { className: 'denglu', onClick: _this.button },\n            '\\u767B\\u5F55'\n          )\n        )\n      );\n    } else {\n      return React.createElement('div', null);\n    }\n  }\n});";
    }
  }, "login");
})(window, ysp);