(function (win, ysp) {
  ysp.runtime.Model.extendLoadingModel({
    getData_control1_EbdNUR: function (elem) {},
    doAction_uiControl1_oTfUO0: function (data, elem) {
      if (data.eventType == "Inquire") {
        $(elem).find('#_easyui_tree_8').click();
      } else if (data.eventType == 'Reimburse') {
        $(elem).find('#_easyui_tree_2').find('span.tree-hit').click();
      }
    },
    getTemplate_uiControl1_oTfUO0: function () {
      var selfTemplate = "module.exports = React.createClass({\n  handle: function(data, eventType) {\n    var handler = this.props.customHandler;\n    handler && handler({\n      data,\n      eventType\n    });\n  },\n  render: function() {\n    var me = this\n    return (\n      <div className='home'>\n       \t<li\tonClick={()=>{\n            me.handle(\"\",\"Upcoming\");\n          }}><span><span className='Upcoming'></span>\u5F85\u529E</span></li>\n        <li\tonClick={()=>{\n            me.handle(\"\",\"loan\");\n          }}><span><span className='loan'></span>\u501F\u6B3E</span></li>\n        <li\tonClick={()=>{\n            me.handle(\"\",\"Reimburse\");\n          }}><span><span className='Reimburse'></span>\u62A5\u9500</span></li>\n        <li onClick={()=>{\n            me.handle(\"\",\"Inquire\");\n          }}><span><span className='Inquire'></span>\u67E5\u8BE2</span></li>\n      </div>\n    )\n  }\n});\n\n\n";
      return '"use strict";\n\nmodule.exports = React.createClass({\n  displayName: "exports",\n\n  handle: function handle(data, eventType) {\n    var handler = this.props.customHandler;\n    handler && handler({\n      data: data,\n      eventType: eventType\n    });\n  },\n  render: function render() {\n    var me = this;\n    return React.createElement(\n      "div",\n      { className: "home" },\n      React.createElement(\n        "li",\n        { onClick: function onClick() {\n            me.handle("", "Upcoming");\n          } },\n        React.createElement(\n          "span",\n          null,\n          React.createElement("span", { className: "Upcoming" }),\n          "\\u5F85\\u529E"\n        )\n      ),\n      React.createElement(\n        "li",\n        { onClick: function onClick() {\n            me.handle("", "loan");\n          } },\n        React.createElement(\n          "span",\n          null,\n          React.createElement("span", { className: "loan" }),\n          "\\u501F\\u6B3E"\n        )\n      ),\n      React.createElement(\n        "li",\n        { onClick: function onClick() {\n            me.handle("", "Reimburse");\n          } },\n        React.createElement(\n          "span",\n          null,\n          React.createElement("span", { className: "Reimburse" }),\n          "\\u62A5\\u9500"\n        )\n      ),\n      React.createElement(\n        "li",\n        { onClick: function onClick() {\n            me.handle("", "Inquire");\n          } },\n        React.createElement(\n          "span",\n          null,\n          React.createElement("span", { className: "Inquire" }),\n          "\\u67E5\\u8BE2"\n        )\n      )\n    );\n  }\n});';
    },
    getData_control2_SRXzDn: function (elem) {},
    doAction_uiControl2_zvx70n: function (data, elem) {},
    getTemplate_uiControl2_zvx70n: function () {
      var selfTemplate = "const {\n  ButtonGroup,\n  NavBar,\n  PopoverTrigger,\n  Popover,\n  Button,\n  Tabs,\n  Icon,\n  List,\n  Switch\n} = AMUITouch2;\nimport {\n  Header,\n  HeaderLeft,\n  HeaderRight\n} from 'ysp-interior-components';\nmodule.exports = React.createClass({\n  render: function() {\n    return (\n      <div>\n        <Header amStyle=\"primary\" style={{padding:\"0\"}}  title=\"\u7F51\u4E0A\u62A5\u9500\u7CFB\u7EDF\">\n          <HeaderLeft >\n            <AMUI.Button amStyle=\"primary\" style={{margin:\"0\"}} \n              onClick={()=>{}}><span></span>x</AMUI.Button>\n          </HeaderLeft>\n          <HeaderRight >\n            <AMUI.Button amStyle=\"primary\" style={{margin:\"0\"}} \n              onClick={()=>{}}><span></span>\u5237\u65B0</AMUI.Button>\n          </HeaderRight>\n          \n        </Header>\n      </div>\n    )\n  }\n});";
      return "\"use strict\";\n\nvar _yspInteriorComponents = require(\"ysp-interior-components\");\n\nvar _AMUITouch = AMUITouch2,\n    ButtonGroup = _AMUITouch.ButtonGroup,\n    NavBar = _AMUITouch.NavBar,\n    PopoverTrigger = _AMUITouch.PopoverTrigger,\n    Popover = _AMUITouch.Popover,\n    Button = _AMUITouch.Button,\n    Tabs = _AMUITouch.Tabs,\n    Icon = _AMUITouch.Icon,\n    List = _AMUITouch.List,\n    Switch = _AMUITouch.Switch;\n\nmodule.exports = React.createClass({\n  displayName: \"exports\",\n\n  render: function render() {\n    return React.createElement(\n      \"div\",\n      null,\n      React.createElement(\n        _yspInteriorComponents.Header,\n        { amStyle: \"primary\", style: { padding: \"0\" }, title: \"\\u7F51\\u4E0A\\u62A5\\u9500\\u7CFB\\u7EDF\" },\n        React.createElement(\n          _yspInteriorComponents.HeaderLeft,\n          null,\n          React.createElement(\n            AMUI.Button,\n            { amStyle: \"primary\", style: { margin: \"0\" },\n              onClick: function onClick() {} },\n            React.createElement(\"span\", null),\n            \"x\"\n          )\n        ),\n        React.createElement(\n          _yspInteriorComponents.HeaderRight,\n          null,\n          React.createElement(\n            AMUI.Button,\n            { amStyle: \"primary\", style: { margin: \"0\" },\n              onClick: function onClick() {} },\n            React.createElement(\"span\", null),\n            \"\\u5237\\u65B0\"\n          )\n        )\n      )\n    );\n  }\n});";
    }
  }, "Home");
})(window, ysp);